Create Fetch_DT.py
SriPrarabdha/LegalBrain-VectorSearch pull request #1
Opened 2023-05-24 15:06 UTC by devdhruvper

Code to fetch data for any given year by - Dhruv Talan

2023-05-24 18:40 UTC, SriPrarabdha commented
@devdhruvper  Rather that printing out the results store them in a array of dicts . The final array 'data' should have all the data in following form
`
data = [
                {
                     'id' : '567549' ,
                     'date' : 'month+Year' ,
                     'tagline' : "Heading of that judgment" ,
                      'judgment' : "Actual Judgment .... " ,
               },
                {
                     'id' : '567548' ,
                     'date' : 'month+Year' ,
                     'tagline' : " Heading of that judgment" ,
                      'judgment' : "Actual Judgment .... ",
               },
           ]
`

2023-05-24 18:41 UTC, SriPrarabdha commented
You will get id in url ,for date use 'datetime' module in python

2023-05-24 21:52 UTC, devdhruvper commented
Changed into required JSON format

2023-05-25 14:30 UTC, SriPrarabdha commented
@devdhruvper There seems to be issue with the date as you can see in the ss below date for a judgment on December 1950 is tagged as 16/1950
Try to debug this!!
<img width="641" alt="json" src="https://github.com/SriPrarabdha/LegalBrain-VectorSearch/assets/89463301/706ce3e3-4665-4582-a10b-e678f47ac862">

2023-05-25 14:38 UTC, SriPrarabdha requested changes

2023-05-25 14:38 UTC, SriPrarabdha commented on Fetch_DT.py
> +    ad_doc = page_div.find("div", class_="ad_doc")
remove this ad_doc instead add
try:
     judgment = page_div.find("pre").text
    except:
     judgment = ""
     p_tags = page_div.find_all("p")
     for p_tag in p_tags:
      judgment += p_tag.text
data.append({'id': no, 'date': f"{i}/{Year}", 'tagline': tagline , 'judgment':judgment})

2023-05-25 18:08 UTC, devdhruvper commented
solved the bug in months and added judgment.

2023-05-25 19:52 UTC, merged